name: Docker Image CI

env:
  tag: ghbuilder

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
 #   - uses: actions/checkout@v2

 #   - name: Set up Docker Buildx
 #     id: buildx
 #     uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        # context: .  # not needed; using defult git contenxt
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{env.tag}}:latest
        


  #  - name: Build the Docker image
  #    run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
